version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      # Add your RDS environment variables here
      # - DATABASE_URL=postgresql://user:password@host:5432/dbname
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 