branch-defaults:
  main:
    environment: stacktracker-env-v5
    group_suffix: null
global:
  application_name: stacktracker-app-v3
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
